### ISSUE TITLE
error when generating location if sensor is using multipacket purchases

### ISSUE THREAD

**Issue by gradoj** [emergotechnologies/helium-positioning-api#24]
An internal error is thrown when console api returns too many results for hotspots.
![image](https://user-images.githubusercontent.com/7544765/205457106-96bc8006-4e3e-4808-91f5-32e5cd7538db.png)
I believe this happens if the console is setup to purchases more than one packet.

```
  File "working/location/helium-positioning-api/src/helium_positioning_api/api.py", line 35, in predict
    prediction = NearestNeighborModel().predict(uuid=uuid)
  File "working/location/helium-positioning-api/src/helium_positioning_api/Models.py", line 43, in predict
    hotspots = self.get_hotspots(uuid)
  File "working/location/helium-positioning-api/src/helium_positioning_api/Models.py", line 33, in get_hotspots
    return [Hotspot(**h) for h in integration["data"]["req"]["body"]["hotspots"]]
TypeError: string indices must be integers
INFO:helium_api_wrapper.DeviceApi:Getting Device Integration Events for uuid xxxxxx-xxxxxxxx-xxxxxxxxxxx
{'category': 'uplink', 'data': {'integration': {'id': 'xxxxxxxxxxx-xxxx-4xxxx2-xxx-xxxxxxxxx', 'name': 'lht65-vercel', 'status': 'success'}, 'req': {'body': 'Request body is too long and cannot be displayed properly.', 'headers': {'Content-Type': 'application/json'}, 'method': 'post', 'url': 'http://redacted', 'url_params': []}}, 'description': 'Request sent to <<"lht65">>', 'device_id': 'xxxxx-xxxx-xxxx-xxxxx-xxxxxxxxx', 'frame_down': None, 'frame_up': None, 'organization_id': 'xxxxxxxx', 'reported_at': '1670045954208', 'router_uuid': 'xxxxxxxxxxxx', 'sub_category': 'uplink_integration_req'}
INFO:     127.0.0.1:55682 - "GET /predict/xxxxxxxxxxxx-xxxxxxxxx-xxxxxxxxxx HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
```

**Comment by gradoj** [comment]
i disable multipacket purchase and all previously failing sensors are working. i don't know the exact limitation of length(number of hotspots) but this must be a limitation on the helium console api. _Request body is too long and cannot be displayed properly._

**Comment by fabiankay** [comment]
Working on some adjustments in the helium_api_wrapper. It will resolve and return hotspots from the integration event and return it for usage in positioning api.

**Comment by simonpfeifhofer** [comment]
@fabiankay resolved?

**Comment by fabiankay** [comment]
Latest helium_api_wrapper version solves this issue by using previous events (not ideal).

**Recommendation**: Limit Hotspots or returned information in the console configuration of a device.

**Comment by gradoj** [comment]
It is easy to limit the number the number of hotspots to purchase the packet from. Do you know where that limit is? eg. 100 hotspots?

**Comment by simonpfeifhofer** [comment]
@gradoj maybe the following link helps: https://docs.helium.com/use-the-network/console/multi-packets/#configuring-multiple-packets.
