### ISSUE TITLE
Folium

### ISSUE THREAD

**Issue by simonpfeifhofer** [emergotechnologies/helium-positioning-api#64]
Folium is not part of the packages, however it's in use in helium_positioning_demo.ipynb. 
Should it be included in requirements.txt or should there be some hint that it's necessary to install it manually?

**Comment by fabiankay** [comment]
Would not include in requirements since it is only needed for the demo notebook.
Hint suggesting its installation would be a possible solution - maybe it can be added in the Notebook as additional command.
